.DEFAULT: help
help:
	@echo "make get-dev"
	@echo "      install python 3.5 and python3-pip"
	@echo "make peer_1"
	@echo "       run peer_1"
	@echo "make peer_2"
	@echo "       run peer_2"
	@echo "make peer_3"
	@echo "       run peer_3"
	@echo "make peer_4"
	@echo "       run peer_4"
	@echo "make peer_5"
	@echo "       run peer_5"
	@echo "make peer_6"
	@echo "       run peer_6"
	@echo "make peer_7"
	@echo "       run peer_7"
	@echo "make peer_8"
	@echo "       run peer_8"
	@echo "make peer_9"
	@echo "       run peer_9"
	@echo "make peer_10"
	@echo "       run peer_10"


get-dev:
	sudo apt-get -y install python3.5 python3-pip

peer_1:
	python3 peer_1.py
peer_2:
	python3 peer_2.py
peer_3:
	python3 peer_3.py
peer_4:
	python3 peer_4.py
peer_5:
	python3 peer_5.py
peer_6:
	python3 peer_6.py
peer_7:
	python3 peer_7.py
peer_8:
	python3 peer_8.py
peer_9:
	python3 peer_9.py
peer_10:
	python3 peer_10.py

